config/routes.rb
Rails.application.routes.draw do



  use_doorkeeper do
  skip_controllers :authorizations, :applications,
    :authorized_applications
  end


  namespace :api do
	devise_for :users,
	   only: :registrations,
	   controllers: {
	     registrations: 'api/users/registrations'
	   }

    #User
  
    match '/activate_account', to: 'users#activate_account', via: 'post'
    match '/resend_activation_code', to: 'users#resend_activation_code', via: 'post'
    match '/change_password', to: 'users#change_my_password', via: 'put'
    match '/change_username', to: 'users#change_my_username', via: 'put'
    match '/my_profile', to: 'users#my_profile', via: 'get'
    match '/my_tokens', to: 'users#my_tokens', via: 'get'
    match '/users/:id', to: 'users#show', via: 'get'
    match '/edit_my_profile', to: 'users#edit_my_profile', via: 'put'
    match '/send_a_new_password', to: 'users#send_new_password', via: 'post'
    match '/index' ,to:'users#index' ,via:'get'
    match '/upload_avatar', to: 'users#upload_avatar', via: 'put'

    # Article
    resources :articles
    match 'article/upload_avatar/:id', to: 'articles#upload_avatar', via: 'put'
  match 'article/sort', to: 'articles#index', via: 'post'
  match 'article/search', to: 'articles#search', via: 'post'
  match '/userList', to:'articles#userList', via: 'get'
    resources :favorites
    resources :add_category_tables
  end
end

app/controllers/api/add_category_tables_controller.rb
class Api::AddCategoryTablesController < ApplicationController
  before_action :set_add_category_table, only: [:show, :edit, :update, :destroy]
  before_action :doorkeeper_authorize!,except:[:index]
  before_action :admin_authorize!
  # GET /add_category_tables
  # GET /add_category_tables.json
  def index
    @add_category_tables = AddCategoryTable.all
    render json:@add_category_tables , status:200
  end
  # GET /add_category_tables/1
  # GET /add_category_tables/1.json
  def show
    render json:@add_category_tables,status:200
  end

  # GET /add_category_tables/new
  def new
    @add_category_table = AddCategoryTable.new
  end

  # GET /add_category_tables/1/edit
  def edit
  end

  # POST /add_category_tables
  # POST /add_category_tables.json
  def create
    @add_category_table = AddCategoryTable.new(add_category_params)
      if @add_category_table.save
        render json:@add_category_table,status:200
      else
        render json: @add_category_table.errors
      end
  end

  # PATCH/PUT /add_category_tables/1
  # PATCH/PUT /add_category_tables/1.json
  def update
      if @add_category_table.update(add_category_params)
        render json: @add_category_table,status:200
      else
        render json: @add_category_table.errors, status:400
      end
  end

  # DELETE /add_category_tables/1
  # DELETE /add_category_tables/1.json
  def destroy
    if @add_category_table.destroy
      render json:@add_category_table,status:200
    else
      render json:@add_category_table.errors,status:400
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_category_table
      @add_category_table = AddCategoryTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def add_category_params
      params.permit(:cat_title)
    end
end

app/helpers/add_category_tables_helper.rb
module AddCategoryTablesHelper
end

app/views/add_category_tables/_form.html.erb
<%= form_for(add_category_table) do |f| %>
  <% if add_category_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add_category_table.errors.count, "error") %> prohibited this add_category_table from being saved:</h2>

      <ul>
      <% add_category_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/add_category_tables/edit.html.erb
<h1>Editing Add Category Table</h1>

<%= render 'form', add_category_table: @add_category_table %>

<%= link_to 'Show', @add_category_table %> |
<%= link_to 'Back', add_category_tables_path %>

app/views/add_category_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add Category Tables</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_category_tables.each do |add_category_table| %>
      <tr>
        <td><%= link_to 'Show', add_category_table %></td>
        <td><%= link_to 'Edit', edit_add_category_table_path(add_category_table) %></td>
        <td><%= link_to 'Destroy', add_category_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add Category Table', new_add_category_table_path %>

app/views/add_category_tables/new.html.erb
<h1>New Add Category Table</h1>

<%= render 'form', add_category_table: @add_category_table %>

<%= link_to 'Back', add_category_tables_path %>

app/views/add_category_tables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_add_category_table_path(@add_category_table) %> |
<%= link_to 'Back', add_category_tables_path %>