config/routes.rb
Rails.application.routes.draw do



  use_doorkeeper do
  skip_controllers :authorizations, :applications,
    :authorized_applications
  end


  namespace :api do
	devise_for :users,
	   only: :registrations,
	   controllers: {
	     registrations: 'api/users/registrations'
	   }

    #User
  
    match '/activate_account', to: 'users#activate_account', via: 'post'
    match '/resend_activation_code', to: 'users#resend_activation_code', via: 'post'
    match '/change_password', to: 'users#change_my_password', via: 'put'
    match '/change_username', to: 'users#change_my_username', via: 'put'
    match '/my_profile', to: 'users#my_profile', via: 'get'
    match '/my_tokens', to: 'users#my_tokens', via: 'get'
    match '/users/:id', to: 'users#show', via: 'get'
    match '/edit_my_profile', to: 'users#edit_my_profile', via: 'put'
    match '/send_a_new_password', to: 'users#send_new_password', via: 'post'
    match '/index' ,to:'users#index' ,via:'get'
    match '/upload_avatar', to: 'users#upload_avatar', via: 'put'

    # Article
    resources :articles
    match 'article/upload_avatar/:id', to: 'articles#upload_avatar', via: 'put'
  match 'article/sort', to: 'articles#index', via: 'post'
  match 'article/search', to: 'articles#search', via: 'post'
  match '/userList', to:'articles#userList', via: 'get'
    resources :favorites
    resources :add_category_tables
  end
end

app/models/registration_code.rb
class RegistrationCode < ApplicationRecord
  belongs_to :user
  def expired?
    (self.updated_at + 1.hours) <  0.seconds.from_now
  end
end

app/controllers/api/registration_codes_controller.rb
class Api::RegistrationCodesController < ApplicationController
  before_action :set_registration_code, only: [:show, :edit, :update, :destroy]

  # GET /registration_codes
  # GET /registration_codes.json
  def index
    @registration_codes = RegistrationCode.all
  end

  # GET /registration_codes/1
  # GET /registration_codes/1.json
  def show
  end

  # GET /registration_codes/new
  def new
    @registration_code = RegistrationCode.new
  end

  # GET /registration_codes/1/edit
  def edit
  end

  # POST /registration_codes
  # POST /registration_codes.json
  def create
    @registration_code = RegistrationCode.new(registration_code_params)

    respond_to do |format|
      if @registration_code.save
        format.html { redirect_to @registration_code, notice: 'Registration code was successfully created.' }
        format.json { render :show, status: :created, location: @registration_code }
      else
        format.html { render :new }
        format.json { render json: @registration_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registration_codes/1
  # PATCH/PUT /registration_codes/1.json
  def update
    respond_to do |format|
      if @registration_code.update(registration_code_params)
        format.html { redirect_to @registration_code, notice: 'Registration code was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_code }
      else
        format.html { render :edit }
        format.json { render json: @registration_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_codes/1
  # DELETE /registration_codes/1.json
  def destroy
    @registration_code.destroy
    respond_to do |format|
      format.html { redirect_to registration_codes_url, notice: 'Registration code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_code
      @registration_code = RegistrationCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_code_params
      params.fetch(:registration_code, {})
    end
end

app/helpers/registration_codes_helper.rb
module RegistrationCodesHelper
end

app/views/registration_codes/_form.html.erb
<%= form_for(registration_code) do |f| %>
  <% if registration_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registration_code.errors.count, "error") %> prohibited this registration_code from being saved:</h2>

      <ul>
      <% registration_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registration_codes/edit.html.erb
<h1>Editing Registration Code</h1>

<%= render 'form', registration_code: @registration_code %>

<%= link_to 'Show', @registration_code %> |
<%= link_to 'Back', registration_codes_path %>

app/views/registration_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registration Codes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registration_codes.each do |registration_code| %>
      <tr>
        <td><%= link_to 'Show', registration_code %></td>
        <td><%= link_to 'Edit', edit_registration_code_path(registration_code) %></td>
        <td><%= link_to 'Destroy', registration_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration Code', new_registration_code_path %>

app/views/registration_codes/new.html.erb
<h1>New Registration Code</h1>

<%= render 'form', registration_code: @registration_code %>

<%= link_to 'Back', registration_codes_path %>

app/views/registration_codes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_registration_code_path(@registration_code) %> |
<%= link_to 'Back', registration_codes_path %>